language: rust

os: linux
arch: ppc64le

branches:
  only:
    - master

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo build --all --no-default-features --features="std utils clap"
  - cargo build --all --no-default-features
  - cargo test
  - cargo test --no-default-features
