[package]
authors = ["Nobody_Nowhere <63668759+rand12345@users.noreply.github.com>"]
name = "stm32f407_controller"
edition = "2021"
version = "0.1.0"

[[bin]]
name = "main"
# test = false
# bench = false
[lib]
harness = false

[[test]]
name = "integration"
harness = false

[features]
default = ["defmt", "ze40", "foxess", "tcp_debug"] 
tcp_debug = []
precharge = []
v65 = []
defmt = []      
byd = ["dep:byd_protocol"]
tesla_m3 = ["dep:tesla_m3_bms"]
pylontech = ["dep:pylontech_protocol"]
ze50 = ["dep:ze50_bms"]
ze40 = ["dep:ze40_bms"]
foxess = ["dep:foxess_protocol"]
solax = ["dep:solax_protocol"]

[dependencies]

cortex-m = { version = "0.7.6", features = [
    "inline-asm",
    "critical-section-single-core",
    "linker-plugin-lto",
] }
cortex-m-rt = "0.7.0"
defmt = { version = "0.3" }
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
embedded-io-async = { version = "0.6.0" }
embassy-sync = { version = "0.3.0", features = ["defmt"] }
embassy-executor = { version = "0.3.0", features = ["nightly", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers", "arch-cortex-m", "executor-thread", "executor-interrupt"] }
embassy-time = { version = "0.1.3", default-features = false, features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-32_768",
] }
embassy-stm32 = { version = "0.1.0", features = [
    "defmt",
    "nightly",
    "embedded-sdmmc",
    "stm32f407ve",
    "unstable-pac",
    "memory-x",
    "time-driver-any",
] } 
embassy-futures = { version = "^0" }

embedded-sdmmc = { git = "https://github.com/embassy-rs/embedded-sdmmc-rs", rev = "a4f293d3a6f72158385f79c98634cb8a14d0d2fc" }

embassy-net = { version = "0.1", features = [
   "defmt", "tcp", "udp", "dhcpv4", "medium-ethernet", "nightly"
] } 
futures = { version = "0.3.17", default-features = false, features = [
    "async-await",
] }
static_cell = { version = "1.1", features = ["nightly"]}

embedded-alloc = "0.5.0"
heapless = { version = "0.7.16", features = ["defmt"] }
lazy_static = { version = "1", default-features = false, features = [
    "spin_no_std",
] }

tickv = {path = "../tickv/"}
# 2kbit eeprom
eeprom24x = "0"
# 64kbit eeprom
w25q = "0.2" # consider https://github.com/tweedegolf/w25q32jv/blob/main/src/lib.rs
siphasher = "0.3"

embedded-hal = "0.2.7"
rand_core = {version = "0.6.4", default-features = false}
rust-mqtt = {path = "../rust-mqtt", default-features = false, features = ["no_std"]}
embedded-nal-async = { version = "0.6.0" }
miniserde = {version = "^0", default-features = false}
httparse = {version = "1", default-features = false}

ze40_bms = {git = "ssh://git@github.com/rand12345/toucan_controller.git",optional = true}
ze50_bms = {git = "ssh://git@github.com/rand12345/toucan_controller.git",optional = true}
tesla_m3_bms = {git = "ssh://git@github.com/rand12345/toucan_controller.git",optional = true, features = ["debug"]}
foxess_protocol = {git = "ssh://git@github.com/rand12345/toucan_controller.git", optional = true, features = ["defmt"]}
solax_protocol = {git = "ssh://git@github.com/rand12345/toucan_controller.git", optional = true, features = ["defmt"]}
pylontech_protocol = {git = "ssh://git@github.com/rand12345/toucan_controller.git", optional = true}
byd_protocol = {git = "ssh://git@github.com/rand12345/toucan_controller.git", optional = true, features = ["v65"]}
bms_standard = {git = "ssh://git@github.com/rand12345/toucan_controller.git"}
url-lite = "0.1.0"
crc16 = "0"
dotenvy_macro = "0.15.7"
# one-wire-bus = "0.1.1"
# ds18b20 = "0.1.1"
# testing st7735
# st7735-lcd = "0.8.1"
# embedded-graphics = "0.7.1"
# once_cell = {version = "1", default-features = false}

[dev-dependencies]
defmt-test = "0.3.0"
bxcan = "0.7.0"
solax_protocol = {git = "ssh://git@github.com/rand12345/toucan_controller.git", features = ["defmt"]}

