name: Builder

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
      releaseNotes:
        description: 'Release Notes'
        required: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: []
        output_name: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup build target
      run: rustup target add thumbv7em-none-eabi

    - name: Build
      run: |
        cargo build --release --features "${{ inputs.features }}"
        mv ./target/thumbv7em-none-eabi/release/main ./target/thumbv7em-none-eabi/release/"${{ inputs.output_name }}"
