name: Create Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
      releaseNotes:
        description: 'Release Notes'
        required: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      MQTTHOST: "91.121.93.94"
      MQTTPORT: 1883
      MQTTCLIENTID: "Client_${{ github.run_id }}"
      MQTTUSERNAME: ""
      MQTTPASSWORD: ""
      MQTTBASETOPIC: "Toucan_Controller_${{ github.run_id }}/test_data"
      MQTTWILLTOPIC: "Toucan_Controller_${{ github.run_id }}/will"
      MQTTRETAIN: true
      MQTTINTERVAL: 10
      MQTTQOS: 0
      RS485BAUD: 9600
      NTPSERVER: "216.40.34.37:123"
      TIMEZONE: "Europe/London"

    steps:
    - uses: actions/checkout@v3
      id: checkout 
    - uses: battila7/get-version-action@v2
      id: get_version
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add build target
      run: rustup target add thumbv7em-none-eabi
    - name: Build ze40 -> FoxESS
      run: |
        cargo build --release --features  "ze40 foxess modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./target/thumbv7em-none-eabi/release/ze40_foxess.bin
    - name: Build ze50 -> FoxESS
      run: |
        cargo build --release --features  "ze50 foxess modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./target/thumbv7em-none-eabi/release/ze50_foxess.bin

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset-0
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/thumbv7em-none-eabi/release/ze40_foxess.bin
        asset_name: "ZE40 => FoxESS"
        asset_content_type: application/octet-stream
    - name: Upload Release Asset
      id: upload-release-asset-1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/thumbv7em-none-eabi/release/ze50_foxess.bin
        asset_name: "ZE40 => FoxESS"
        asset_content_type: application/octet-stream

    - name: Clean up
      run: |
        cargo clean
        