name: Create Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
      releaseNotes:
        description: 'Release Notes'
        required: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      MQTTHOST: "91.121.93.94"
      MQTTPORT: 1883
      MQTTCLIENTID: "Client_${{ github.run_id }}"
      MQTTUSERNAME: ""
      MQTTPASSWORD: ""
      MQTTBASETOPIC: "Toucan_Controller_${{ github.run_id }}/test_data"
      MQTTWILLTOPIC: "Toucan_Controller_${{ github.run_id }}/will"
      MQTTRETAIN: true
      MQTTINTERVAL: 10
      MQTTQOS: 0
      RS485BAUD: 9600
      NTPSERVER: "216.40.34.37:123"
      TIMEZONE: "Europe/London"
      UNIQUE_NAME: ""

    steps:
    - uses: actions/checkout@v3
      id: checkout 
    - uses: battila7/get-version-action@v2
      id: get_version
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add build target
      run: rustup target add thumbv7em-none-eabi
    - name: Build ze40 -> FoxESS
      run: |
        cargo build --release --features  "ze40 foxess modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze40_foxess.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze40_foxess.bin
          path: ze40_foxess.bin
    - name: Build ze50 -> FoxESS
      run: |
        cargo build --release --features  "ze50 foxess modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze50_foxess.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze50_foxess.bin
          path: ze50_foxess.bin

    - name: Clean up
      run: |
        cargo clean

  pre-release:
    name: "pre-release"
    runs-on: "ubuntu-latest"
    needs: [build_and_release]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: true
          title: "New Build"
          files: |
            ze40_foxess.bin
            ze50_foxess.bin