name: Create Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
      releaseNotes:
        description: 'Release Notes'
        required: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     features:
    #       - ""
    #       - "ze40 solax modbus_bridge"
    #       - "ze40 byd modbus_bridge"
    #       - "ze40 pylontech modbus_bridge"
    #       - "ze50 foxess modbus_bridge"
    #       - "ze50 solax modbus_bridge"
    #       - "ze50 byd modbus_bridge"
    #       - "ze50 pylontech modbus_bridge"
    #     output_name:
    #       - "ze40_foxess.bin"
    #       - "ze40_solax.bin"
    #       - "ze40_byd.bin"
    #       - "ze40_pylontech.bin"
    #       - "ze50_foxess.bin"
    #       - "ze50_solax.bin"
    #       - "ze50_byd.bin"
    #       - "ze50_pylontech.bin"

    steps:
    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Build and Release 0
      id: build_and_release_0
      uses: ./.github/workflows/build.yml
      with:
        features: "ze40 foxess modbus_bridge"
        output_name: "ze40_foxess.bin"

    # - name: Build and Release 1
    #   id: build_and_release_1
    #   uses: ./.github/workflows/build.yml
    #   with:
    #     features: ${{ fromJson(needs.build_and_release.outputs.matrix)[1].features }}
    #     output_name: ${{ fromJson(needs.build_and_release.outputs.matrix)[1].output_name }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset-0
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/thumbv7em-none-eabi/release/"ze40_foxess.bin"
        asset_name: "ZE40 => FoxESS"
        asset_content_type: application/octet-stream
    # - name: Upload Release Asset
    #   id: upload-release-asset-1
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./target/thumbv7em-none-eabi/release/${{ fromJson(needs.build_and_release.outputs.matrix)[1].output_name }}
    #     asset_name: ${{ fromJson(needs.build_and_release.outputs.matrix)[1].output_name }}
    #     asset_content_type: application/octet-stream
    - name: Clean up
      run: |
        cargo clean
        