name: Create Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
      releaseNotes:
        description: 'Release Notes'
        required: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      MQTTHOST: "91.121.93.94"
      MQTTPORT: 1883
      MQTTCLIENTID: "Client_${{ github.run_id }}"
      MQTTUSERNAME: ""
      MQTTPASSWORD: ""
      MQTTBASETOPIC: "Toucan_Controller_${{ github.run_id }}/test_data"
      MQTTWILLTOPIC: "Toucan_Controller_${{ github.run_id }}/will"
      MQTTRETAIN: true
      MQTTINTERVAL: 10
      MQTTQOS: 0
      RS485BAUD: 9600
      NTPSERVER: "216.40.34.37:123"
      TIMEZONE: "Europe/London"
      UNIQUE_NAME: ""
      MODBUS_REMOTE: "1.2.3.4:502"

    steps:
    - uses: actions/checkout@v3
      id: checkout 
    - uses: battila7/get-version-action@v2
      id: get_version
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add build target
      run: rustup target add thumbv7em-none-eabi
    # ZE40 --------------------------
    - name: Build ze40 -> FoxESS
      run: |
        cargo build --release --features  "ze40 foxess modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze40_foxess.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze40_foxess.bin
          path: ze40_foxess.bin

    - name: Build ze40 -> Solax
      run: |
        cargo build --release --features  "ze40 solax modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze40_solax.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze40_solax.bin
          path: ze40_solax.bin

    - name: Build ze40 -> BYD
      run: |
        cargo build --release --features  "ze40 byd modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze40_byd.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze40_byd.bin
          path: ze40_byd.bin
          
    - name: Build ze40 -> Goodwe GW6000
      run: |
        cargo build --release --features  "ze40 goodwe modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze40_goodwe.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze40_goodwe.bin
          path: ze40_goodwe.bin

    - name: Build ze40 -> PylonTech
      run: |
        cargo build --release --features  "ze40 pylontech modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze40_pylontech.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze40_pylontech.bin
          path: ze40_pylontech.bin

    - name: Build ze40 -> PylonTech Force H2
      run: |
        cargo build --release --features  "ze40 forceh2 modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze40_pylontech_forceh2.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze40_pylontech_forceh2.bin
          path: ze40_pylontech_forceh2.bin
    # ZE50 --------------------------
    - name: Build ze50 -> FoxESS
      run: |
        cargo build --release --features  "ze50 foxess modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze50_foxess.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze50_foxess.bin
          path: ze50_foxess.bin

    - name: Build ze50 -> Solax
      run: |
        cargo build --release --features  "ze50 solax modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze50_solax.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze50_solax.bin
          path: ze50_solax.bin

    - name: Build ze50 -> BYD
      run: |
        cargo build --release --features  "ze50 byd modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze50_byd.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze50_byd.bin
          path: ze50_byd.bin

    - name: Build ze50 -> Goodwe
      run: |
        cargo build --release --features  "ze50 goodwe modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze50_goodwe.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze50_goodwe.bin
          path: ze50_goodwe.bin

    - name: Build ze50 -> PylonTech
      run: |
        cargo build --release --features  "ze50 pylontech modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze50_pylontech.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze50_pylontech.bin
          path: ze50_pylontech.bin

    - name: Build ze50 -> PylonTech Force H2
      run: |
        cargo build --release --features  "ze50 forceh2 modbus_bridge"
        mv ./target/thumbv7em-none-eabi/release/main ./ze50_pylontech_forceh2.bin
    - uses: actions/upload-artifact@v3
      with:
          name: ze50_pylontech_forceh2.bin
          path: ze50_pylontech_forceh2.bin

    - name: Clean up
      run: |
        cargo clean

  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"
    needs: [build_and_release]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release"
          prerelease: false
          title: "Release ${{github.ref_name}}"
          files: |
            ze40_foxess.bin
            ze40_solax.bin
            ze40_byd.bin
            ze40_goodwe.bin
            ze40_pylontech.bin
            ze40_pylontech_forceh2.bin
            ze50_foxess.bin
            ze50_solax.bin
            ze50_byd.bin
            ze50_goodwe.bin
            ze50_pylontech.bin
            ze50_pylontech_forceh2.bin
