name: Rust


on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"

    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  rust_toolchain: nightly-2023-12-20

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MQTTHOST: "91.121.93.94"
      MQTTPORT: 1883
      MQTTCLIENTID: "Client_${{ github.run_id }}"
      MQTTUSERNAME: ""
      MQTTPASSWORD: ""
      MQTTBASETOPIC: "Toucan_Controller_${{ github.run_id }}/test_data"
      MQTTWILLTOPIC: "Toucan_Controller_${{ github.run_id }}/will"
      MQTTRETAIN: true
      MQTTINTERVAL: 10
      MQTTQOS: 0
      RS485BAUD: 9600
      NTPSERVER: "216.40.34.37:123"
      TIMEZONE: "Europe/London"

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add build target
      run: rustup target add thumbv7em-none-eabi
    - name: Build all IO options
      run: cargo build --release --features "spi display ntp mqtt modbus_client"
    - name: Build ze40 -> FoxESS
      run: cargo build --release --features "ze40 foxess ntp mqtt modbus_bridge"
    - name: Build ze40 -> Solax
      run: cargo build --release --features "ze40 solax ntp mqtt modbus_bridge"
    - name: Build ze40 -> BYD
      run: cargo build --release --features "ze40 byd ntp mqtt modbus_bridge"
    - name: Build ze40 -> Goodwe
      run: cargo build --release --features "ze40 goodwe ntp mqtt modbus_bridge"
    - name: Build ze40 -> Force H2
      run: cargo build --release --features "ze40 forceh2 ntp mqtt modbus_bridge"
    - name: Build ze40 -> Pylontech
      run: cargo build --release --features "ze40 pylontech ntp mqtt modbus_bridge"
    - name: Build ze50 -> Solax
      run: cargo build --release --features "ze50 solax ntp mqtt modbus_bridge"
